name: CI Hardware Info

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-hardware:
    name: Gather Hardware Information
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Environment Variables
        run: env | sort

      - name: Print CPU Information
        run: lscpu

      - name: Print Memory Information
        run: free -h

      - name: Print Disk Space Information
        run: df -h

      - name: Print Kernel and OS Info
        run: uname -a

      - name: Print Detailed OS Info
        run: cat /etc/os-release

      - name: Print PCI Devices
        run: lspci || echo "lspci not available"

      - name: Print USB Devices
        run: lsusb || echo "lsusb not available"

      - name: Print Installed Packages
        run: dpkg-query -W || echo "dpkg-query not available"

      - name: Print Power Management Info
        run: cat /sys/class/power_supply/BAT0/uevent || echo "No battery info available"

      - name: Print Temperature Sensors
        run: sensors || echo "sensors not available, try installing lm-sensors"

      - name: Print Network Interface Details
        run: ip addr show

      - name: Print Running Processes
        run: ps aux --sort=-%cpu | head -n 20
